import type { DetectionResult } from "../../shared/types/detection";

const AI_ALT_PATTERNS = [
  /generated by/i,
  /ai[- ]generated/i,
  /midjourney/i,
  /dall[- ]?e/i,
  /stable diffusion/i,
  /adobe firefly/i,
  /imagen\b/i,
  /ai art/i,
  /artificial intelligence/i,
];

const AI_CLASS_PATTERNS = [
  /ai[-_]?gen/i,
  /ai[-_]?image/i,
  /generated[-_]?image/i,
  /synthetic[-_]?image/i,
  /midjourney/i,
];

const AI_DATA_ATTRS = [
  "data-ai-generated",
  "data-synthetic",
  "data-source-ai",
  "data-generator",
];

export function classifyImageElement(img: HTMLImageElement): DetectionResult | null {
  const alt = img.alt ?? "";
  const className = img.className ?? "";

  for (const pattern of AI_ALT_PATTERNS) {
    if (pattern.test(alt)) {
      return {
        isAI: true,
        confidence: 0.85,
        source: "dom-heuristic",
        contentType: "image",
        detail: `alt text: "${alt.slice(0, 60)}"`,
      };
    }
  }

  for (const pattern of AI_CLASS_PATTERNS) {
    if (pattern.test(className)) {
      return {
        isAI: true,
        confidence: 0.8,
        source: "dom-heuristic",
        contentType: "image",
        detail: `class: "${className.slice(0, 60)}"`,
      };
    }
  }

  for (const attr of AI_DATA_ATTRS) {
    if (img.hasAttribute(attr)) {
      return {
        isAI: true,
        confidence: 0.9,
        source: "dom-heuristic",
        contentType: "image",
        detail: `attribute: ${attr}="${img.getAttribute(attr)}"`,
      };
    }
  }

  return null;
}
